ws_lista1 = list(["uno",2,3,4.5])
print(ws_lista1)
print(ws_lista1[3])
print(type(ws_lista1[3]))
print(len(ws_lista1))
ws_lista1.append("cinco")
print(ws_lista1)
ws_lista1.insert(2,"2.5")
print(ws_lista1)
ws_lista1.extend([6,7,"ocho"])
print(ws_lista1)
ws_lista1.pop(1)
print(ws_lista1)
ws_lista1.pop(-1)
print(ws_lista1)
ws_lista1.remove("cinco")
print(ws_lista1)
ws_lista1.clear()
print(ws_lista1)

ws_lista1.extend([4,78,56,23,True,True,False])
print(ws_lista1)

ws_lista1.reverse()
print(ws_lista1)

ws_lista1.sort()
print(ws_lista1)

ws_lista1.sort(reverse=True)
print(ws_lista1)
